# Generated by Django 5.1.2 on 2025-11-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='default_peak_order_limit',
            new_name='default_order_limit_second',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='max_order_limit',
            new_name='order_limit_first',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='peak_order_limit',
            new_name='order_limit_second',
        ),
    ]
