# Generated by Django 5.1.2 on 2025-11-02 18:33

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='slOrderslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='ID of the Order being traded', max_length=100)),
                ('security_id', models.CharField(help_text='ID of the security being traded', max_length=100)),
                ('exchange_segment', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange')], help_text='Segment of the exchange', max_length=50)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='SELL', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units to trade')),
                ('order_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP_LOSS', 'Stop Loss Order')], default='STOP_LOSS', max_length=20)),
                ('product_type', models.CharField(choices=[('INTRADAY', 'Intraday'), ('DELIVERY', 'Delivery')], default='INTRADAY', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at which the order is set', max_digits=10)),
                ('trigger_price', models.DecimalField(decimal_places=2, help_text='Trigger price for stop-loss orders', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempNotifierTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAccountOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pnl_status', models.FloatField()),
                ('expenses', models.FloatField()),
                ('closing_balance', models.FloatField()),
                ('order_count', models.IntegerField()),
                ('actual_profit', models.FloatField()),
                ('day_open', models.BooleanField(default=False)),
                ('day_close', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_account_overviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySelfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_check', models.IntegerField(help_text='Rate from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mind_check', models.IntegerField(help_text='Rate from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expectation_level', models.IntegerField(help_text='Rate from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('patience_level', models.IntegerField(help_text='Rate from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('previous_day_self_analysis', models.IntegerField(help_text='Rate from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pnl_status', models.CharField(blank=True, help_text='Profit and Loss Status of the day', max_length=100, null=True)),
                ('order_count', models.IntegerField(blank=True, help_text='Total number of orders of the day', null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='The date and time when the self-analysis was created')),
                ('overall_advice', models.CharField(blank=True, help_text='Profit and Loss Status of the day', max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DhanKillProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.JSONField()),
                ('order_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.JSONField()),
                ('date', models.DateField()),
                ('order_count', models.IntegerField()),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eod_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sod_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255, unique=True)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_growth', models.DecimalField(decimal_places=2, help_text='Expected growth as a percentage (e.g., 15.5 for 15.5%)', max_digits=20)),
                ('no_of_weeks', models.PositiveIntegerField()),
                ('average_weekly_gain', models.DecimalField(decimal_places=2, help_text='Average weekly gain as a percentage (e.g., 2.5 for 2.5%)', max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRTCUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('usage_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('plan_name', models.CharField(max_length=255)),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accumulated_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gained_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGoalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('plan_name', models.CharField(max_length=255)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gained_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='reports.weeklygoalreport')),
            ],
        ),
    ]
